### ISSUE TITLE
Spike: See what it would take to have plot.ly, bokeh, matpotlib work

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards_server#108]
matplotlib notebook mode references `IPython.notebook.kernel.*`. I suspect the others do similar things. What shims would we need to provide to have the three libs in the title work in the dashboard server?

**Comment by jhpedemonte** [comment]
matplotlib request in ipywidgets: https://github.com/ipython/ipywidgets/issues/378

**Comment by jdfreder** [comment]
Here's a related conversation on the Plotly side of things: https://github.com/plotly/plotly.py/issues/408

**Comment by jdfreder** [comment]
You should be able to used the output widget to capture these things.  Have you tried that yet?

**Comment by parente** [comment]
@jdfreder Have not. We're using the jupyter-js-notebook OutputAreaModel/View as the top-level wrapper for dashboard "cells". Are you saying that putting OutputWidget in those cells where we know there's custom JS coming from the backend will help somehow?

Most of the problem I see with matplotlib's notebook implementation, for example, is that it makes direct references to `IPython.notebook` which just isn't there. I'm missing how OutputWidget will help (mostly out of ignorance).

**Comment by jdfreder** [comment]
Ah no, it's my fault, I misread what the problem was - the missing globals.  I thought you were having trouble capturing the output because a lack of an output area.  Sounds like you've got that covered though.

**Comment by parente** [comment]
An outcome I'd like to see from this is a statement of compatibility in the README here about what libraries we do and don't work with. I don't think we're going to be able to make **everything** work during the transition period in which libraries are adapting from working in classic notebook to alternative application containers (jupyter lab, standalone, ...)

**Comment by parente** [comment]
https://github.com/jupyter-incubator/dashboards_server/blob/master/public/js/widget-manager.js#L174

Try adding more functions here with good comments about what shims are provided and for what library.

**Comment by dalogsdon** [comment]
For matplotlib, I was able to add some shim code alongside the DeclWidgets shims in our widget manager. It's mostly just stubbing out some notebook functionality that dashboard server doesn't support, but one function does need to access output area data which requires us to poke into the internals of the output area (phosphor observable list) to extract the required data.

**Comment by parente** [comment]
Thanks for giving this a shot. That's not a terrible starting shim for matplotlib. Now I wonder what it looks like if you do bokeh too. Any overlap or all new shims?

**Comment by dalogsdon** [comment]
For Bokeh things mostly worked. It accessed the comm manager from `Jupyter` rather than `IPython`. 

There is a comm-related error causing `push_notebook()` to stop working (which breaks the sliders updating the chart). In the notebook, Bokeh registers a comm target immediately, but in the dashboard server it is delayed a bit. A comm_open message is received before the Bokeh target is registered, causing the comm to not work even after the target is registered.

I'm currently digging into this issue to see if we can get the target registered or the handler delayed until it is registered.

**Comment by dalogsdon** [comment]
Ah, didn't notice that the same error happens in the notebook. I was seeing it work when refreshing or re-running the cells.

**Comment by dalogsdon** [comment]
The actual error I am seeing is:

`Class 418b81d5-6076-4769-97e5-bc62a3925bc8 not found in registry @ jupyter-js-services.js:3130`

Looks like the same error is happening in the notebook.

**Comment by dalogsdon** [comment]
The error doesn't happen when running cells individually, specifically when running `output_notebook()` cell and allowing time for the JS to load. This is not an option in dashboard server, however.

The issue https://github.com/bokeh/bokeh/issues/3639 gives the same error in other cases and looks to be related to the loading of JS from an external (CDN) source. An inline option is mentioned; I can see if that is possible for us to set.

**Comment by dalogsdon** [comment]
One way to solve it is to use inline mode by calling `output_notebook(bokeh.resources.INLINE)` to load Bokeh.

**Comment by dalogsdon** [comment]
There is also a rendering issue since Bokeh uses a table and the output area has the class `rendered_html`. This causes some of our styling to leak into the plot. We might need to make our rendered_html handling more sophisticated to ignore content added by other libraries.

**Comment by jhpedemonte** [comment]
My initial thought was to somehow monkey-patch Bokeh to wait for its scripts to load before executing anything. But this is probably going to be an issue with other toolkits as well.

So here's my new proposal: we execute all code cells in a loop, then wait for result to come back and pass that to `jupyter-js-output-area` to handle. The latter is what adds HTML/JS to the DOM. When handling results, we can add a check to see if any `<script>` were added to the DOM. If so, we add `onLoad` handlers and queue up any remaining results until those scripts have loaded.

This would be a generic solution to this issue that would work for Bokeh as well as other toolkits.

**Comment by dalogsdon** [comment]
@jhpedemonte This is an interesting potential solution. I opened #135 to investigate. For this issue we can recommend specific coding style to make things work.

**Comment by dalogsdon** [comment]
Trying plotly, I am able to get it working in the notebook, but there is an issue that breaks dashboards because it undefines requirejs globals. They do have a fix in https://github.com/plotly/plotly.py/pull/412, but it is not yet released.

**Comment by dalogsdon** [comment]
I'm also seeing the "run all" problem like with Bokeh. The plot does not render because it is looking for a global `Plotly` which is not yet defined. Looking to see if there is a similar workaround like the Bokeh inline mode.

**Comment by dalogsdon** [comment]
The problem with 'run all' with plotly was that requirejs was used to create a 'plotly' module, and then the plotly module was required to set `window.Plotly`. However, this operation is asynchronous, and the plot rendering function attempts to access `window.Plotly` before it is set. There needs to be another fix to plotly to wrap the plot creation in a require call. I made a fork to try this and it worked. I will see about creating a PR on plotly.

**Comment by dalogsdon** [comment]
I opened a PR with the libraries working and with an example notebook showing all 3. Currently still 2 issues:

1. Bokeh plot has some borders around it. I opened https://github.com/bokeh/bokeh/issues/4012 to deal with this.
2. Plotly has a requirejs error. I did a quick fix in a fork, and so will need to update the example notebook once it is fixed. I opened https://github.com/plotly/plotly.py/pull/420 to deal with this.

**Comment by parente** [comment]
:beers: for the other bug reports and 2 line fix.

**Comment by bryevdv** [comment]
FYI going to push a PR to Bokeh today to add `try`/`catch` around the notebook comms bit, which should ameliorate the problem in https://github.com/bokeh/bokeh/issues/4143 It just means that if notebook comms cannot be set up for whatever reason, that things will not fall over (`push_notebook` will not work int that case, of course)
