### ISSUE TITLE
Extra spacing caused by visible widget-area in every output area

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards_server#109]
The notebook server hides widget-areas until they are needed. We're currently showing them whether they're populated or not. Their styling, unfortunately, introduces some whitespace (margin or padding, I haven't checked) that causes things to look misaligned.

Notebook server:

<img width="1138" alt="screen shot 2016-02-17 at 9 22 54 pm" src="https://cloud.githubusercontent.com/assets/153745/13132788/ed71221c-d5c3-11e5-8fb6-7796d4f6fb38.png">

Dashboard server:

<img width="1160" alt="screen shot 2016-02-17 at 9 23 00 pm" src="https://cloud.githubusercontent.com/assets/153745/13132790/f0662940-d5c3-11e5-973f-4b418dcd4f45.png">

**Comment by dalogsdon** [comment]
Maybe we can just use an `:empty` pseudo class to hide/collapse the widget area.

**Comment by dalogsdon** [comment]
@jhpedemonte noticed this as well and we observed some padding.
