### ISSUE TITLE
Notebooks with spaces in filename don't work

### ISSUE THREAD

**Issue by jhpedemonte** [jupyter-incubator/dashboards_server#111]
Rename `variable_inspector.ipynb` to `Variable Inpsector.ipynb` (the Notebook allows you do this when you change a notebook title and add a space, it creates a file with space in name). Trying to load that in server leads to many errors on the kernel gateway.

**Comment by parente** [comment]
On the kernel gateway? That's odd. The kernel gateway doesn't even know the code is coming from a notebook.

**Comment by parente** [comment]
If this is easy and you do it now, sure. I'll just retag it as 0.2.0 as I merge the PR. (It's what I've been doing anyway for things that get in early that were 0.3.0 before.)

We'll just say tomorrow is the cutoff for 0.2.0.

**Comment by jhpedemonte** [comment]
`dashboard-proxy:server:error Failed to load notebook data for +0ms Variable%20Inspector.ipynb [Error: Error loading notebook]`
