### ISSUE TITLE
Clean up data/ dir

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards_server#120]
Strawman. Whoever takes this can come up with something better:

* [x] move the decl widget and ipywidget test notebooks into `test` (most of the ones we have in the top level at the moment)
    - NOTE: Declarative widgets examples now must be bundled dashboards, packaged along with the `urth_components` directory. See the two `data/*` targets at bottom of Makefile.
* [x] create one or two really simple top level notebooks that introduce what the dashboard server is and where to go to get the tools to arrange and deploy notebooks to it
* [x]  maybe during build copy one or two of the demos from the dashboards or decl widget repos here (trick will be finding ones that work without massive additional installs or without the shims we're exploring in #108). Or maybe always install during the Docker.server build which we call the demo image anyway.
* [x] Remove data/decl-widgets-chart, data/decl-widgets, and data/test/test_layout_declarativewidgets since they no longer work now that decl widgets are not available globally

**Comment by parente** [comment]
Candidates for demos to copy during build:

* taxi demo (already has a make target)
* Streaming meetup with the webgl globe (expand examples make target?)
* ArxivBokeh from decl widgets repo (or one of the other Bokeh ones if Bokeh works in #108)

**Comment by Lull3rSkat3r** [comment]
Grabbing this.

**Comment by jhpedemonte** [comment]
Updated description to note that declarative widgets examples/tests must now be bundled dashboards.

**Comment by parente** [comment]
:+1:

**Comment by dalogsdon** [comment]
> ArxivBokeh from decl widgets repo (or one of the other Bokeh ones if Bokeh works in #108)

I'll probably be writing a plotting demo notebook based on results of #108 that we could use here. It could be Bokeh-based or use all 3 libraries looked at in #108 (matplotlib, Bokeh, plotly) if they all run properly in a single notebook.

**Comment by parente** [comment]
I'm grabbing this.
