### ISSUE TITLE
Fix gridstack layout on mobile devices

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards_server#126]
Gridstack already does ... something ...  in response to small window widths. I think it reflows the cell order in an unexpected way so that label cells, for example, are no longer stacked above their targets. See cougar notebook for an example https://github.com/jupyter-incubator/dashboards_server/blob/master/data/test/test_style_match.ipynb

**Comment by parente** [comment]
Confirmed it's not just use but seems to be the default GS behavior:

From http://troolee.github.io/gridstack.js/demo/responsive.html

![screen shot 2016-03-07 at 7 47 56 am](https://cloud.githubusercontent.com/assets/153745/13569912/fb0ee5ac-e438-11e5-9700-e0e243058045.png)

becomes

![screen shot 2016-03-07 at 7 48 02 am](https://cloud.githubusercontent.com/assets/153745/13569914/fea4c9c0-e438-11e5-9d9c-22e2348c8241.png)

If 1 and 3 are title / headers as is typical in our dashboards, we'd like it to reflow as 1,2,3,4,5 right down the page to keep 1 above its content (2), and 3 above its content (4,5). 

I'm not sure how to achieve this in practice for all situation. It depends on semantics between the grid cells that go beyond simple x/y layout coords.

**Comment by parente** [comment]
@dalogsdon would you mind looking at this next?

**Comment by parente** [comment]
If #139 is the fix, I'm fine with that.

**Comment by dalogsdon** [comment]
> It depends on semantics between the grid cells that go beyond simple x/y layout coords.

This implies a multi-layer approach where multiple notebook cells go into each dashboard layout cell. Also within a single dashboard cell there could be another layout, perhaps horizontal or vertical at the simplest level, or a full Gridstack layout within each dashboard cell.

**Comment by parente** [comment]
Yea. I *really* don't want to go down that path. The simple layout mechanism we have is a big win. Can't expect users to do much more.

I wonder, though, if simple rules would do the trick? Example: if there's a mardown cell above me in x/y, make sure it stays above me. Sort of a simple constraint based layout.

**Comment by dalogsdon** [comment]
@jhpedemonte suggests the simple approach of using notebook order as that will most likely already be in a logical order. I will use that approach within #139 to resolve this issue.

**Comment by parente** [comment]
:+1:

**Comment by jhpedemonte** [comment]
No @parente, you gotta use the new reaction emojis!

**Comment by parente** [comment]
Ah dang it!

**Comment by parente** [comment]
Resolved by #140.
