### ISSUE TITLE
Add integration tests to check ipywidgets, declwidgets

### ISSUE THREAD

**Issue by jhpedemonte** [jupyter-incubator/dashboards_server#130]
We should add some integration tests to check the state of simple notebooks containing ipywidgets and declarative widgets.  For the bundled dashboard PR, we added the use of `jsdom` in the integration tests, so we can parse the HTML response and test the DOM directly.

Testing declarative widgets will likely have to be its own make target since we'll have to create a bundled dashboard ZIP which includes the declwidgets Polymer elements. See the `bundled-dashboard` & `taxi-demo` Makefile targets.

Any other of our test notebooks which should be turned into tests?

**Comment by dalogsdon** [comment]
Do we need Selenium-level tests to interact with the widgets to ensure they are hooked up properly, or is it sufficient to examine the HTML page?

**Comment by parente** [comment]
My vote is sticking with HTML inspection for now.

**Comment by dalogsdon** [comment]
After writing the initial tests to do the HTML check I remembered that code cells are always sent empty and are populated as a result of the execution result / comm Websocket messages. We may need to take the Selenium approach so we can wait for those elements to get populated.

**Comment by dalogsdon** [comment]
Discussed with @jhpedemonte if there is an intermediate approach. We may be able to use [nightmare](http://www.nightmarejs.org/). I'll look into this.

**Comment by dalogsdon** [comment]
I have a test working locally (OSX) using nightmare. However, I have been having trouble getting it running in a Docker container (Linux). I attempted the suggestions in  https://github.com/segmentio/nightmare/issues/224#issuecomment-182470015, but the tests are hanging. Currently debugging and seeing if possible to run in a container.

**Comment by dalogsdon** [comment]
I finally got the tests working in the Docker container. Just gotta keep on adding packages until it works :wink:.

I added a new `Dockerfile.test` that installs more packages since we need to run Xvfb to use Electron on Linux. This means an additional 200MB install after the `chown` from the `Dockerfile.server` :sob:.

**Comment by parente** [comment]
If you've got this stuff in a branch somewhere, can you submit a PR so we can look at how bad it's getting before you go too much further?

**Comment by dalogsdon** [comment]
Yeah, I'm finishing getting it working from the Makefile target, then I will push the branch.

**Comment by dalogsdon** [comment]
Initial work can be seen in https://github.com/dalogsdon/dashboards_server/commit/0e883e34e9f9cf1ae5463d6a6aa031d85eddc608

There are currently 2 simple tests that check for an ipywidget and a declarative widget. I can make these tests more detailed with actual widget interaction now that we are using nightmare.

Additionally I can try to minimize the extra installs to decrease the testing duration.

**Comment by parente** [comment]
As I run out the door, it doesn't look too bad. Any estimate on the build/test runtime? (Yay for keeping all the stuff isolated in its own Dockerfile.)

**Comment by dalogsdon** [comment]
From timing on my laptop:

`make integration-test` takes 48 seconds if all Docker steps are cached.
In the typical case, if a file is changed causing the ADD to rerun, then it takes 2m 16s.

**Comment by jhpedemonte** [comment]
Talking to Drew, the large increase in time has to do (most likely) with the `apt-get` commands. Since the test Dockerfile inherits from the server one, whenever a file is changed in the server code, this invalidates the cache for **all** of the test Docker container.

Possible solutions:
1. Create entirely separate test Docker image, instead of inheriting from the server one.
2. For test file access, use a volume mount instead of `ADD`/`chown`.
3. Both of the above?

**Comment by parente** [comment]
> Create entirely separate test Docker image, instead of inheriting from the server one.

Or just lob the test assets into the `Dockerfile.server` ahead of the `ADD` command. I still believe that's the definition of a *developer* image not something we recommend people build and use in production. I don't mind test prereqs in there.

**Comment by dalogsdon** [comment]
> Or just lob the test assets into the Dockerfile.server ahead of the ADD command.

:+1: Least complicated approach. I can move the installs over, making the test Dockerfile just run Xvfb before the tests.

**Comment by dalogsdon** [comment]
There should now be minimal change to test runtime under the common case using `make integration-test` during development.
