### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards_server#131]
At some point, we want a stable release on npm so that users can:

```
npm install -g jupyter_dashboards_server
jupyter_dashboards_server --IP 0.0.0.0 --PORT 12345 --DATA_DIR /wherever/here --KERNEL_GATEWAY_URL http://my.kernelgateway.org/
```

~~I believe this is blocked by #46 since we're currently git cloning and building things~~ I believe we're going to need a parameter that let's the user point the server at an alternative `data/` directory since that will now be squirreled away somewhere in a `node_modules` tree, probably global. The same might be true for an optional landing login page when using OAuth.

Also, we need to check on the rules for publishing packages with `jupyter` in the npm name. @jdfreder, did you or anyone end up reserving the jupyter org on npm?

TODOs

* [x]  `bin/jupyter-dashboards-server` (renamed)
* [x] CLI option to point to a data directory (NOTEBOOKS_DIR already exists, but make it PWD relative if set, not install location relative)
* [x] Make target to bundle frontend assets and release (`make release`, but not yet tested because we're not ready to release)
* [X] fix `var BufferList = require('../node_modules/websocket/vendor/FastBufferList');` ref (try this, then try assuming j-d-s is installed and the vendor lib is a peer)
* [x] Some way to test release builds without actually releasing (`make install-test` added)
* [x] --help option for CLI (simple cat of config.json since that's our only record of supported opts and defaults)

**Comment by jdfreder** [comment]
No, no Jupyter org.  We have no nice way of dealing with org level permissions atm.  The way I've been going about it is, I create and publish the package, add anyone who else who maintains the package, and add new people as the need arises.
