### ISSUE TITLE
Replace gridstack.js with minimal layout library

### ISSUE THREAD

**Issue by jhpedemonte** [jupyter-incubator/dashboards_server#139]
We use Gridstack.js in the Notebook's dashboard extension in order to allow the user to move/resize cells, to create the dashboard layout. But on the dashboard server, we don't need any of the interactivity that Gridstack provides -- we just need to layout the cells.

Therefore, it might be better to create our own small library to do the layout.  It would be much smaller than Gridstack and would also clean up our code since we wouldn't have to work around Gridstack functionality that we need to shut off anyway.

This may also help us fix the single column view (issue #126), since we can handle the layout ourselves.

**Comment by dalogsdon** [comment]
We will attempt to use this as the resolution of #126.

**Comment by dalogsdon** [comment]
I'll also base this off the work for #39 so we can avoid the issue of temporarily altering the Gridstack version. Therefore, this will also resolve #39.

**Comment by dalogsdon** [comment]
I generated the layout CSS client-side the same way Gridstack did. After discussing with @jhpedemonte, I reduced the number of breakpoints to 2: 1140px for the normal width to match the notebook and 768px for large mobile devices with the cells having reduced width. Below 768px the cells will render in notebook/DOM order, full width.

**Comment by parente** [comment]
Resolved by #140.
