### ISSUE TITLE
"no layout" dashboards handled incorrectly

### ISSUE THREAD

**Issue by jhpedemonte** [jupyter-incubator/dashboards_server#145]
I think we are handling notebooks without layout metadata incorrectly. Take a look at our **test_no_layout.ipynb** notebook. When opened in the dashboard server, we show nothing.

The dashboard extension runs through an algorithm for notebooks without layout metadata, determining which cells contain output (and should therefore be shown) and hiding others. But such an algorithm doesn't make sense for dashboard server.

Instead, I propose that we show all of the cells in a single-column, full width (if no notebook-level `metadata.urth.dashboard` property is set). We should also log a message to the browser console. This works as a quick way to upload and display a notebook, without worrying about installing/using the dashboard & bundler extensions.

**Comment by parente** [comment]
Just put the cells in the regular DOM flow. Make sure we style so that empty cells have no padding, margin, etc. so that there's no unnecessary whitespace.

**Comment by dalogsdon** [comment]
This is just defaulting to report layout (https://github.com/jupyter-incubator/dashboards/issues/203), so the console could log something like "No dashboard layout found, defaulting to report layout."
