### ISSUE TITLE
Changes to redeployed of bundled dashboard do not appear in UI on refresh

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards_server#150]
Looks like we're now caching notebooks after first load somewhere server-side. Need to read from disk every time to account for redeploys.

Behavior used to be correct.

**Comment by parente** [comment]
Here's the problem:

https://github.com/jupyter-incubator/dashboards_server/blob/master/app/notebook-store.js#L109

**Comment by dalogsdon** [comment]
> premature optimization?

**Comment by parente** [comment]
Unfortunately, simply taking out all refs to store breaks upload tests and suddenly starts giving us websocket disconnects after load. (WTH).

Could use another pair of eyes.

**Comment by dalogsdon** [comment]
I had thought we deleted the file from cache on upload, I'll have a peek with my eyes.

**Comment by dalogsdon** [comment]
https://github.com/jupyter-incubator/dashboards_server/blob/master/app/notebook-store.js#L357

Should clean the cache. Perhaps the path is wrong or this isn't getting called properly.
