### ISSUE TITLE
Support report layout

### ISSUE THREAD

**Issue by dalogsdon** [jupyter-incubator/dashboards_server#157]
https://github.com/jupyter-incubator/dashboards/issues/203 will introduce a simpler dashboard "report" layout:

> **Report mode:** a simple view which shows cells in notebook order, single column and full width. The only action available to the user is whether to show/hide each cell.

We should support this layout once it is implemented in the dashboards notebook extension.

**Comment by dalogsdon** [comment]
Discussed with @jhpedemonte, and we decided that https://github.com/jupyter-incubator/dashboards/issues/203 will be handled as a subset of the grid layout. Therefore, this should just automatically work in the dashboard server. We will probably just end up closing this issue after verifying that it works as expected.

**Comment by parente** [comment]
Is the dashboard authoring for report mode computing height for each cell? Or will logic need to be added over here to interpret and compute the height of each output area?

I ask because #145 is about rendering notebooks that have NO layout metadata as if they were laid out top to bottom in report mode with all cells with output showing.

**Comment by dalogsdon** [comment]
Yes, it should still be computing height.

**Comment by dalogsdon** [comment]
The nature of jupyter-incubator/dashboards#203 has changed and is now handing report layout as a separate (non-Gridstack) layout. The dashboard server will have to handle this. This may now overlap with #145 a bit as the dashboard will default to the report layout if no dashboard layout metadata.

**Comment by parente** [comment]
Probably best if @dalogsdon and @jameslmartin pair on the two items in tandem. Good intro for @jameslmartin too.
