### ISSUE TITLE
Use ipywigets' new embed manager?

### ISSUE THREAD

**Issue by jhpedemonte** [jupyter-incubator/dashboards_server#189]
Recent versions of ipywidgets include a layer specifically for embedding. See https://github.com/ipython/ipywidgets/blob/master/jupyter-js-widgets/src/embed-webpack.js.  Use by [web4 example](https://github.com/ipython/ipywidgets/tree/master/jupyter-js-widgets/examples/web4).

Do we want to make use of this?

**Comment by parente** [comment]
This is probably a no-op now that we're webpacking everything anyway, right?

**Comment by jhpedemonte** [comment]
No, we don't need this. It does things that don't affect/concern us.
