### ISSUE TITLE
Spike: Replace OutputAreaModel/Widget

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards_server#191]
Create a very simple replacement for OutputAreaModel capable of handling all of the methods used in `dashboards.js#messageHandlers`.

Details in #141.

**Comment by jhpedemonte** [comment]
Attempted to create our own output area handler ([patch here](https://github.com/jhpedemonte/dashboards_server/commit/18b4809908c093a62b02c6435885e596a2f917a4)). Works for simple output and simple ipywidgets, but fails on plotting libs, etc (not sure why). But as I get further, I'm just recreating `output-area` from `jupyter-js-notebook`. I'm thinking it's not worth pursuing this if I'm just going to end up with `output-area` anyway.

@jasongrout @blink1073: What do you recommend as the course of action here? As it currently stands, `output-area` only seems to have one notebook dependency: `notebook/nbformat`. Should `output-area` be made fully generic for use both within and outside of the notebook? Or will non-notebook users have to always create their own impl?

**Comment by blink1073** [comment]
The intent was limit the sources of "truth" for the notebook format.  We already have https://github.com/jupyter/nbformat/blob/master/nbformat/v4/nbformat.v4.schema.json.  We could move the output area to `jupyter-js-ui` and split `notebook/nbformat` into two parts, would that help?

**Comment by jasongrout** [comment]
Our intent was also that you would be able to import the output area from the jupyter-js-notebook package and use it standalone. I'm not sure exactly what you mean by "made fully generic for use both within and outside of the notebook". The dependency on notebook/nbformat is solely for the `createOutput` function that goes from the notebook format to an output model. Would it help if we split that function into a separate file? Then you could import just the `jupyter-js-notebook/lib/output-area/widget` file and use the output area.

**Comment by jasongrout** [comment]
Actually, sorry, that `createOutput` goes from an output model to an output widget. It uses the *interfaces* defined in `notebook/nbformat`, and internally creates a MimeBundle (also from `notebook/nbformat`).

But I'm still confused at what you're trying to do. We had intended that you could use the output area widget outside of the notebook (and pretty soon we'll be trying to do just that in JupyterLab). Would it help to have a quick call about this? Or perhaps you can join us tomorrow for our weekly JupyterLab meeting (noon Eastern) and we discuss it after status reports?

**Comment by parente** [comment]
@jhpedemonte or I can probably hope on the JLab call tomorrow. We started a conversation about the issues we hit trying to use output-area in dashboard server over here https://github.com/jupyter-incubator/dashboards_server/issues/141#issuecomment-212598097 but it sort of trailed off after a short exchange about the prompts appearing in the widget.

**Comment by jhpedemonte** [comment]
> Our intent was also that you would be able to import the output area from the jupyter-js-notebook package and use it standalone

OK, excellent. This must just be a misunderstanding on my part. From previous discussions, I got the impression that this was only really meant to be used within the notebook and what we were trying to do was particularly supported.

Does it make sense to move this out of *jupyter-js-notebook*? Maybe into **-ui*?

**Comment by blink1073** [comment]
You can `require('jupyter-js-notebook/lib/output-area/widget)` and not use any of the rest of `jupyter-js-notebook`.

**Comment by blink1073** [comment]
If it were in `jupyter-js-ui` the path would be the similar, and we'd have to split the `nbformat` definition arbitrarily.

**Comment by parente** [comment]
We're definitely sticking with jupyter-js-notebook. 

> Does it make sense to move this out of jupyter-js-notebook? Maybe into *-ui?
> But we could have an implementation that just renders a panel of outputs with no prompts and keep that in jupyter-js-ui. (from https://github.com/jupyter-incubator/dashboards_server/issues/141#issuecomment-212599892)

If we want to follow up on these, we should probably open these as PRs or issues against jupyter-js-us/notebook.

**Comment by jhpedemonte** [comment]
Sticking with *jupyter-js-notebook*. Closing this.
