### ISSUE TITLE
A way to break notebook cache

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards_server#208]
Notebooks are cached in memory after the first time they are loaded for viewing as dashboards. The cache is only invalidated if a new version of the notebook is POSTed to /_api/notebooks. However, notebooks might be deployed by simply copying them into place on disk, requiring another way to invalidate cache.

Ideas:

* URL parameter `no_cache=true` forces a reload of the notebook from disk (requires user to know to use it or admin to use it once after overwriting notebooks on disk)
* DELETE /_api/cache resets the entire cache (requires admin to make the call)
* CLI that makes the DELETE call for convenience (icing)
* Improvement to the caching logic to know when a file has changed on disk (hard)

**Comment by jhpedemonte** [comment]
Would this only be available during development (i.e one of the `make dev*` targets)? I would be worried about making this available for production, where anyone could access it.

**Comment by parente** [comment]
Admins need something in production when the move dashboard files around on disk underneath the server. The REST API is nice when you've gone through all the trouble of setting up the bundler to talk to the dashboard server. But in some cases, that's too much effort to setup and you just want download the bundle and drop it into place. Requiring a full dashboard server reset just to deal with busting the cache is bad.

**Comment by jhpedemonte** [comment]
Pairing w/ @jameslmartin. We're going to implement the following:

1. Add `DELETE /cache(/*)` to either delete full cache (no path specified) or just for given path.
2. Create shell script for automating REST invocation to clear cache.

**Comment by jhpedemonte** [comment]
Submitted PR which implements both of the tasks outlined in the previous comment.
