### ISSUE TITLE
Upload with same name as existing should always "overwrite" existing

### ISSUE THREAD

**Issue by dalogsdon** [jupyter-incubator/dashboards_server#209]
Two conditions currently exist:

1. Single-file and bundled dashboards are visibly identical in the UI.
2. Upload overwrites files.

It should follow that uploading a notebook with the same name as an existing bundled dashboard should delete the bundled dashboard, and vice versa.

For example, currently a `some-db.ipynb` dashboard can coexist with a `some-db` bundled dashboard since one is a file and the other is a directory. To reduce confusion about seemingly duplicate dashboards, we can enforce the proposed behavior above during upload.

**Comment by parente** [comment]
I agree that the name alone should be the unique identifier. The use case here, I assume, is that a dashboard might start as a plain notebook and later grow to be bundled. Without the overwrite, it's impossible to move from unbundled to bundled using the API (or back).
