### ISSUE TITLE
Allow hostname, port, and protocol in PUBLIC_LINK

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards_server#218]
https://github.com/jupyter-incubator/dashboards_bundlers/pull/37 makes the response from the dashboard server the default place to get the link to a deployed dashboard instead of a config value in the bundler. Currently, the dashboard server uses a hardcoded URL as the base URL. The original logic in the bundler could compute certain properties such as the hostname, protocol, and port using the Host header. The same should be done here to make configurations more portable.

**Comment by dalogsdon** [comment]
Should the public link be configurable or just purely computed based on the request?

**Comment by parente** [comment]
It's a template in the original code. e.g., "http://{hostname}:8888" would interpolate the hostname from the Host header. "http://hardcoded.com:9999" would still run through the template replacement function, but nothing would get replaced.

**Comment by parente** [comment]
And I know we spoke about this default: 

https://github.com/jupyter-incubator/dashboards_server/blob/687b03d1fbf87fecd6bb5ac2988efb1fa7b96e3c/app/config.js#L81

but now that I see how it's set, it's never going to work in 99% of the cases. Typically, IP is configured to 0.0.0.0 meaning listen on all interfaces.

The default logic should probably be replaced entirely. If PUBLIC_LINK is not set at all, either we should try to compute the URL on the first request to the handler based on the Host and protocol. Or, if it's not set at all, we should not include a link. If it's set, we should follow the template approach described above.

**Comment by dalogsdon** [comment]
I added a PUBLIC_LINK_PATTERN config parameter that can be set and use the `{protocol}`, `{hostname}`, and `{port}` placeholder patterns. A `public-link` module will do the substitution based on a request object. The upload API will not include the link if the PUBLIC_LINK_PATTERN config param is not set.
