### ISSUE TITLE
Markdown headings are clipped

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards_server#220]
<img width="290" alt="screen shot 2016-05-10 at 10 17 35 pm" src="https://cloud.githubusercontent.com/assets/153745/15168179/08e046fc-16fd-11e6-9681-59d0554d4fc3.png">

Clipped in the dashboard server. Not in the notebook. `.dashboard-cell.text-cell` is doing the clipping in dashboard server. What do we do in dashboard preview in the notebook where this does not happen?

**Comment by dalogsdon** [comment]
We initially matched the text styling, maybe they got out of sync or are slightly off.

**Comment by jhpedemonte** [comment]
What code results in this clipping? None of our example/test notebooks show this on Chrome.

**Comment by jhpedemonte** [comment]
I tested H1, H2, H3, comparing between Notebook and dashboards server. Appear the same between both.

**Comment by jhpedemonte** [comment]
Hmm, never mind. Clipping only seems to happen in certain cases. I see it now.

**Comment by parente** [comment]
In a session with other users today, there was some confusion too about why markdown is clipped in notebook dashboard preview and in the dashboard server, but other types of cells overflow in dashboard preview but are clipped in dashboard server. We probably want to look at unifying.
