### ISSUE TITLE
Entire dashboard page shifts when paper-dropdown appears

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards_server#222]
It adds `overflow: hidden` to the body tag when it appears and remove it when it disappears. No idea why. We'll need a workaround.

It looks like our body tag always has a vertical scroll bar present, even when there is no reason for the page to scroll. Can't make it permanently `overflow: hidden` because some dashboards *do* definitely do need to scroll.

**Comment by parente** [comment]
@jhamrick Oops! Didn't mean to click your name here!

**Comment by jhpedemonte** [comment]
Neither Pete nor I could reproduce this today.

**Comment by jhamrick** [comment]
@parente No worries! 😄

**Comment by parente** [comment]
Tried again today and still could not reproduce. I think we can close unless, @jhpedemonte, you want to fix the bug where the scrollbars show even though the content does not extend beyond the bottom of the window. (Looks like a container + navbar height issue.)

**Comment by jhpedemonte** [comment]
> fix the bug where the scrollbars show even though the content does not extend beyond the bottom of the window

Should have been fixed by PR #228
