### ISSUE TITLE
Support updated Declwidgets init API (doesn't return promise)

### ISSUE THREAD

**Issue by jhpedemonte** [jupyter-incubator/dashboards_server#229]
See https://github.com/jupyter-incubator/declarativewidgets/pull/295. The `init` function will now no longer return a `whenReady` Promise.

If we want to stay backwards compatible (for existing bundled dashboards), we can check `init`'s return value to see if it is a Promise (old code) or an object with a `whenReady` property (new code).

**Comment by parente** [comment]
But with that change, the init is now part of the notebook code, not something the dashboard server does, right?

**Comment by jhpedemonte** [comment]
My understanding is that there are now two separate inits:
1. Initialize the extension (what we do in *dashboard.js*)
2. Initialize the Polymer and declwidgets resources (now must be called in a cell).

**Comment by parente** [comment]
OK. Should we future proof now or wait until widgets are out and do it then?

**Comment by jhpedemonte** [comment]
I can take a look with declwidgets master, to future proof.
