### ISSUE TITLE
The server does not execute code cells.

### ISSUE THREAD

**Issue by post2web** [jupyter-incubator/dashboards_server#281]
I only see the markdown cells on the notebook when the dashboad_server renders it.
I have started a kernel gateway like so:
`jupyter kernelgateway` 
To install the dashboard server I download and extract the 0.7.0 release, then run:
```
npm intall
make examples
```
To start:
`./bin/jupyter-dashboards-server --KERNEL_GATEWAY_URL=http://127.0.0.1:8888`
Then when I go to http://localhost:3000/dashboards/test none of the dashboards render the way they are supposed to.

What am I doing wrong? Do I have to start the kernel gateway in a spacial way?

**Comment by parente** [comment]
@jhpedemonte is the current release of the dash server busted because of the Jupyter lab API break?

**Comment by jhpedemonte** [comment]
Ah, yes, hadn't considered that. The 0.7.0 release will probably pull down the latest Jupyterlab, which will break things, as @post2web has found.  **master** is working -- we pinned Jupyterlab 0.1.1.

@post2web, try the **master** branch for the dashboard server.

**Comment by parente** [comment]
Maybe not: 0.7.0 was using the separate jupyter-js-ui, etc. libs prior to the merge into the single jupyterlab package.

https://github.com/jupyter-incubator/dashboards_server/blob/0.7.x/package.json

**Comment by jhpedemonte** [comment]
@post2web Do you see any console errors (or interesting output) from the kernel gateway or the dashboard server when rendering a dashboard? What about errors in the browser console?

**Comment by jhpedemonte** [comment]
@post2web Also, check out the jupyter-incubator/dashboards_setup project. It contains several recipes to quickly start the kernel gateway, notebook server and dashboards server. In particular, check the **docker_deploy** folder.

**Comment by post2web** [comment]
@jhpedemonte There is no console errors also I tried the master and did not work also.
I tried starting the kernel gateway as [shown here](https://github.com/jupyter-incubator/dashboards_setup/blob/master/cf_deploy/manifest.yml): 
`jupyter-kernelgateway --KernelGatewayApp.port=8889 --KernelGatewayApp.ip=127.0.0.1`
But no luck. Notice when I do:
`jupyter-dashboards-server --KERNEL_GATEWAY_URL=http://foo.com`
It acts the same and no console errors.
To me it looks like the dashboard server can not communicate with a kernel and its not complaining about it.

**Comment by jhpedemonte** [comment]
OK, I figured it out. Since you are working from source, in addition to `npm install`, you also have to run `gulp build`. This will build the resources required by the browser.

However, there is a bug in a dependency of a dependency -- you'll have to run `npm install jquery-ui@1.10.5` before doing `gulp build`.

---

I'll create a new release (0.8.0), where these issues are fixed. I might also look to change the behavior of `make build` to do both `npm install` and `gulp build`, to handle a scenario such as this.

**Comment by jhpedemonte** [comment]
NOTE: Running from source is covered in the [readme](https://github.com/jupyter-incubator/dashboards_server#develop-it). The relevant step is `make dev`, which builds the client files before running the dashboard server.

Alternatively, you can [install the actual built program](https://github.com/jupyter-incubator/dashboards_server#install-it) using npm. That doesn't require that you run any make/build commands.

**Comment by parente** [comment]
@jhpedemonte So the 0.7.0 is ok but master is busted?

**Comment by jhpedemonte** [comment]
No, 0.7.0 is broken because of dependency change, but master is working.

**Comment by parente** [comment]
Ok. Should probably cut a 0.8 since it's going to be needed to bring up the VMs for the PyData Carolinas dashboard talk soon. Let me know if you want to do the release or want me to.

/cc @jtyberg @lbustelo

**Comment by parente** [comment]
FYI, the stable 0.7.0 release works fine for me [following the recipe from dashboards_setup/docker_deploy](https://github.com/jupyter-incubator/dashboards_setup/blob/master/docker_deploy/Dockerfile.dashboards#L24).

@post2web said:

> To install the dashboard server I download and extract the 0.7.0 release, then run:

`npm install -g jupyter-dashboards-server` should be all you need to do to get the latest stable release.

**Comment by jhpedemonte** [comment]
Closing. I released 0.8.0, which will fix building from source.
