### ISSUE TITLE
Failed to parse SourceMap: components/dashboard.js.map

### ISSUE THREAD

**Issue by rs2** [jupyter-incubator/dashboards_server#283]
The dashboard server says (in the console):

```
Failed to parse SourceMap: http://servername:3000/components/dashboard.js.map
```

The dashboard (visually) renders OK.

It looks like a responsive UI issue. How can I get more information about the root cause?

**Comment by parente** [comment]
This log line in the JS console just means that the built package does not include a source map file that makes debugging the webpacked JS easier in the browser. It's harmless.

**Comment by jhpedemonte** [comment]
The browser only attempts to query the source map when you have the developer console / inspector open. As @parente stated, this is a harmless error.

**Comment by rs2** [comment]
Where can I read/talk to you guys about the interaction of dashboards server/kernel gateway/thebe/jupyter notebook to understand the workflow and constraints?
