### ISSUE TITLE
Best way to purge published dashboards?

### ISSUE THREAD

**Issue by rs2** [jupyter-incubator/dashboards_server#284]
Also, where do they get stored?

**Comment by parente** [comment]
@jhpedemonte added an admin cli to manage dashboards I think.

**Comment by jhpedemonte** [comment]
@rs2 Correct, there is a `jupyter-dashboard-admin` command-line utility, which allows you to delete dashboards. Run it with the `--help` argument for details.

**Comment by rs2** [comment]
I seem to have neither `jupyter-dashboard-admin` nor `jupyter-dashboards-admin`. Do I need to upgrade my local installation?

**Comment by jhpedemonte** [comment]
This was part of the v0.8.0 release.

**Comment by parente** [comment]
This issue has been inactive for a couple of months. If the admin script in 0.8.0 is missing or not working, feel free to reopen.
