### ISSUE TITLE
Does a notebook kernel get stopped when a user closes a web app page?

### ISSUE THREAD

**Issue by rs2** [jupyter-incubator/dashboards_server#285]
Say, a notebook runs a code to send an email to the user every 10 seconds. A user publishes the notebook to the dashboards server. It runs fine for a minute .then they close the web page.

When will they stop receiving the emails, and how is the life of the kernel controlled?

**Comment by parente** [comment]
It stops when the user closes the page.

**Comment by rs2** [comment]
:+1:

**Comment by parente** [comment]
Hehe. I was worried you were going to ask for the opposite which introduces a management headache.
