### ISSUE TITLE
configure reversed proxy with nginx

### ISSUE THREAD

**Issue by bowenli37** [jupyter-incubator/dashboards_server#287]
I managed to configure a reversed proxy with nginx for jupyter notebook. The gotcha there is that uri is hardcoded to '/'. I referred to the following links:
[nginx.conf](https://gist.github.com/cboettig/8643341bd3c93b62b5c2)
[run notebook on a public server](http://jupyter-notebook.readthedocs.io/en/latest/public_server.html#running-the-notebook-with-a-customized-url-prefix)

I would also like to configure nginx for dashboards server. It seems that uri is also hardcoded in dashboards server as '/'.  I am very new to nginx. Is it possible to configure nginx with out the base_url customization?

**Comment by parente** [comment]
I believe issue #260 has to be fixed for proxying to work.

**Comment by parente** [comment]
#292 makes the dashboard server root relocatable. Proxying should work now. If you give it a shot an hit a new problem, feel free to open another issue.
