### ISSUE TITLE
Where are the copies of the published dashboards stored?

### ISSUE THREAD

**Issue by rs2** [jupyter-incubator/dashboards_server#289]
When you see a list of published dashboards on the default port 3000, how are those dashboards actually stored, together with their bower dependencies?

**Comment by jhpedemonte** [comment]
Currently, if you export a dashboard using Declarative Widgets from the Notebook, it is packaged up into a zip file along with the bower dependencies for Declarative Widgets. Similarly if you use the syntax to associate resources.

Then, when uploading to the dashboard server, the zip is unpacked into the data directory specified by the dashboard server config (`NOTEBOOKS_DIR`). The contents of the zip are stored in a directory with the same name as the zip file. The notebook is set as `index.ipynb` inside that directory.

**Comment by parente** [comment]
@rs2 I'm going to close this. If you have further questions on this topic, feel free to reopen.
