### ISSUE TITLE
Thoughts on single presentation mode

### ISSUE THREAD

**Issue by danielfrg** [jupyter-incubator/dashboards_server#314]
I am currently in need of using the dashboard server to serve a single dashboard instead of the possibility of multiple dashboards and I wanted to get some feedback on possible configs before doing a PR for this.

For some context: I basically want to do my own orchestration/auth of the dashboards outside of the dashboard_server (kubernetes) but I want to use the dashboard_server to render the dashboards.

Basically I want to be able to do something like this: 

```
jupyter-dashboards-server --SINGLE_NOTEBOOK=bokeh_demo.ipynb
or
jupyter-dashboards-server --NOTEBOOKS_DIR=. --SINGLE_PRESENTATION=bokeh_demo
```

And this will serve my dashboard in the root route `/`.

Right now I can do `--PRESENTATION_MODE=true` but I need to know the name of the notebook and the root route just prints a list error, which is the idea from this mode.

Another possible solution is to have the root route redirect to the notebook one if there is only one dashboard. This would be similar to what the bokeh server does when there is only one bokeh app in to deploy.

Thoughts on this?

**Comment by parente** [comment]
If you name the notebook index.ipynb, it will load automatically under any path of the notebook directory, including the root.

**Comment by danielfrg** [comment]
Thats actually what I wanted :) Thanks @parente
