### ISSUE TITLE
Where are Python error tracebacks shown?

### ISSUE THREAD

**Issue by jluttine** [jupyter-incubator/dashboards_server#315]
When opening a dashboard its execution sometimes stops with a red error exclamation mark on the top right corner. It says that there is more information about the error in the console. However, I can't see anything relevant there, nothing about any errors. So where can I find these error messages? I find it very difficult to debug dashboards without this information.

**Comment by jluttine** [comment]
I guess typically the error at least in my case is a Python error. Where can I find the normal traceback for the error?

**Comment by parente** [comment]
If there is a Python traceback, it should display in the JavaScript console in the browser. If it's not appearing there, then the failure is occurring before any of the Python execution most likely.

**Comment by jluttine** [comment]
Thanks, that's perfect! Is this documented somewhere? I just hadn't noticed any info about this. Anyway, thanks a lot! :+1:

**Comment by jluttine** [comment]
Or perhaps the error message in the dashboard could tell to look more info at "the JavaScript console of the browser" instead of "console" which lead me to look at the terminal which was running the dashboard server..
