### ISSUE TITLE
500 Internal Server Error with Declarative widgets

### ISSUE THREAD

**Issue by Skhon09** [jupyter-incubator/dashboards_server#330]
Hi all,

Had to update my docker version on windows to 17.06.0-ce recently.
I've been using  https://github.com/jupyter-incubator/dashboards_setup/tree/master/docker_deploy for 
a while before and everything use to work perfectly.

But after the update, having to rebuild all the images,  whenever I 'deploy to dashboard' a notebook containing some declarative widgets code I get this '500 Internal Server Error' message on my browser with the 'STACK: undefined' error from the server container in the logs.
It works as soon as I remove the declarative widgets.

I'm using the exact same versioning for every libraries and images as before so that's not the issue. I don't think it has something to do with the new Docker version.

Any thoughts?

**Comment by Skhon09** [comment]
I found a workaround:

-Download as Jupyter Dashboards Server bundle(.zip)
-Unzip and upload manually on the data folder of the servers

I guess the issue is more related to the dashboard_bundler and the way a notebook with declarative widgets is zipped and uploaded to the server so I'm closing the issue here.

**Comment by mpekalski** [comment]
@Skhon09 Check if that is not permission issues to the folder in which you store notebooks files for dashboard. Check my PR https://github.com/jupyter-incubator/dashboards_server/pull/336 that explicitly logs the error, and then check your docker logs.

**Comment by Skhon09** [comment]
Thanks for your help but it's not a permission issue for me as it works when declarative widgets are not included.
How did you get more detailed error messages displayed though?

**Comment by mpekalski** [comment]
In `app.js` after line with `console.log('STACK:', err.stack);` add `console.log('ERROR:', err);`
It should display the whole msg in console.
