### ISSUE TITLE
Remove use of bower, just use npm

### ISSUE THREAD

**Issue by jhpedemonte** [jupyter-incubator/dashboards_server#39]
We only use bower for Gridstack and its dependencies (jquery, jquery-ui, lodash). Should just simplify our build and install everything through npm.

**Comment by parente** [comment]
If you want to add this to 0.3.0, feel free.

**Comment by dalogsdon** [comment]
Gridstack 0.2.4 npm module doesn't have any dependencies set, so I updated to 0.2.5 which has the dependencies properly set. There were some minor changes required, see PR #140.

**Comment by parente** [comment]
Resolved by #140.
