### ISSUE TITLE
Indicate a problem when the kernel sends an error message

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards_server#59]
Strawman: some indicator in the nav bar at the top. Sort of like what notebook does when a kernel dies or a websocket disconnects or ... Don't hard code the indicator to kernel errors only though: it's very likely we're going to want to use that same indicator area to give other types of status too.

**Comment by dalogsdon** [comment]
In order to be less obtrusive I may handle some kernel errors specially but will also retain a general message display for future use cases.

**Comment by parente** [comment]
I was thinking a very basic indicator that something is wrong, but not a lot of detail about the problem like you would get out of the console. I suspect the dashboard user really isn't going to care about the cause except when they have to provide debugging information which can be pulled from the console. I was thinking just a red "disconnect" or "broken" or something dot.

**Comment by dalogsdon** [comment]
![image](https://cloud.githubusercontent.com/assets/6362426/13183164/1c9bbfd8-d6fb-11e5-8bb6-e0112c4cab0f.png)

A title will inform the user to check the console. Clicking the error indicator will hide it.

**Comment by dalogsdon** [comment]
Currently it will show on kernel status dead or reconnecting as well as error messages.

**Comment by parente** [comment]
Before I test, does it render in a decent location when login is enabled (because logout appears in the top right too).

**Comment by dalogsdon** [comment]
Ah yes, I intended for it to be to the left of the logout, but it is showing on the right since we are using `pull-right` class which does float layout. I'll update to ensure it is on the left of logout button.
