### ISSUE TITLE
No link to dashboard list if an index notebook exists

### ISSUE THREAD

**Issue by dalogsdon** [jupyter-incubator/dashboards_server#95]
Should the user be able to navigate to the dashboard list (without editing URL manually) if the index notebook exists? Currently the "Home" link in the navbar links to the root URL, so that will show the index notebook. Should there be a separate link to the list (that is shown only if index notebook exists), or would the index notebook be expected to contain a link if desired?

**Comment by parente** [comment]
Yea, we discussed this (having two links in the nav bar) and took no action to start to keep it simple. We can address it in this issue.

**Comment by dalogsdon** [comment]
![image](https://cloud.githubusercontent.com/assets/6362426/13189384/ad434c60-d71c-11e5-801f-2b42763e3de0.png)

**Comment by dalogsdon** [comment]
![image](https://cloud.githubusercontent.com/assets/6362426/13189414/dcebfde0-d71c-11e5-875a-3a3a2ce0135a.png)

**Comment by parente** [comment]
Is the secondary link visible all the time or only when there's an index.ipynb?

**Comment by dalogsdon** [comment]
only when you are at the url `/dashboards/index.ipynb`

**Comment by parente** [comment]
Even better.
