### ISSUE TITLE
Option to disable all chrome on the app

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/dashboards_server#99]
In some cases it's useful to have a single dashboard page standalone without any title, login/logout, or other chrome around it. Think of a single notebook or a set of notebooks deployed by as an app, embedded in another app (e.g., iframed). In this case, the chrome gets in the way.

A nconf option to turn everything off would cover this.

Thoughts?

**Comment by parente** [comment]
@jhpedemonte @dalogsdon

**Comment by dalogsdon** [comment]
Yes, I remember discussing something like this early on before creating the dashboard server.

**Comment by jhpedemonte** [comment]
An nconf option for everything seems fine. But might be good to also allow changing this on a notebook basis. Perhaps through URL:

```
host:8080/dashboards/simple.ipynb?noui=1
host:8080/dashboards/noui/simple.ipynb
host:8080/dashboards/simple.ipynb/noui
```

Something like the latter 2 may be preferable to the first one, since query parameters can cause issues in certain situations (i.e. may get stripped).

**Comment by dalogsdon** [comment]
The middle option would be easier since we can use a different route. The last option may be tricky since we are already doing some path handling in `/dashboards/*`.

**Comment by dalogsdon** [comment]
Route name suggestions other than "noui" are welcome.

**Comment by parente** [comment]
When I opened this, I was thinking about the case where the notebook author wants to deploy the server for a one-off dashboard web app that should NEVER give the user any hint that there's notebooks or a list of notebooks behind the scenes. For example, say I building some business dashboard and I want it to look like I built it as a plain old web app, not using notebooks or dashboard server at all. I don't want to let users muck with the URL and turn on chrome that gives away how it's implemented.

So while I'm fine with having the URL params approach *also* potentially be an option, I'm really looking for the nuke `--no_chrome` option at deploy time. With that option set, the server loads `index.ipynb` (and I as the user better provide it.)

**Comment by dalogsdon** [comment]
`PRESENTATION_MODE` nconf option
`/dashboard-plain/*` route for individual case

**Comment by jhpedemonte** [comment]
> the notebook author wants to deploy the server for a one-off dashboard web app that should NEVER give the user any hint that there's notebooks or a list of notebooks behind the scenes

To clarify: you want the case where the server will only load index.ipynb and nothing else? Even if I know the URL to another notebook on the server (i.e. `.../dashboards/test/test_layout_basic`)?

**Comment by parente** [comment]
> only load index.ipynb and nothing else

No. I'm fine with there being other notebooks on the server that the user might be able to navigate to directly if they know the URL. 

Use case: I want to deploy a scotch dashboard in the dashboard server to the cloud. Then I want to go to my scotch store website and iframe my little dashboard to let users get recommendations while on my site. I don't want users to see a big banner that says Jupyter Dashboards at the top of that iframe. Later, I want to make my scotch recommender a bit more complex: after a user finds a scotch they like, they can click to get more details about that scotch. Maybe that click navigates to a second notebook/dashboard on the server instead of updating everything in line. To implement that, I'll want my index.ipynb notebook to navigate the user's browser (in the iframe) to more_details.ipynb?scotch_name=<the one clicked>.
